kind: Pod
apiVersion: v1
metadata:
  name: calculadora-app
  labels:
    app: calculadora-app
spec:
  containers:
  - name: calculadora-app
    image: calculadora-app:latest
---
kind: Service
apiVersion: v1
metadata:
  name: calculadora-app-service
spec:
  selector:
    app: calculadora-app
  ports:
  - port: 9999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculadora-app-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/calculadora"
        backend:
          service:
            name: calculadora-app-service
            port:
              number: 9999
